

CREATE SEQUENCE BOARD_SEQ;
CREATE TABLE BOARD(
	BOARD_NO NUMBER PRIMARY KEY, --번호
	BOARD_WRITER VARCHAR2(30) REFERENCES MEMBER(MEMBER_ID), --작성자
	BOARD_TITLE VARCHAR2(30) NOT NULL, --제목
	BOARD_CONTENT VARCHAR2(3000) NOT NULL, --내용
	BOARD_REGDATE DATE NOT NULL, --작성일
	BOARD_VIEWS NUMBER DEFAULT 0 NOT NULL, --조회수
	BOARD_LIKE NUMBER DEFAULT 0 NOT NULL, --좋아요
	BOARD_KIND NUMBER NOT NULL --종류
);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'admin','제목','내용',SYSDATE,0,0,1);


SELECT * FROM BOARD;