DROP SEQUENCE CHATROOM_SEQ;
DROP SEQUENCE CHATLIST_SEQ;
DROP SEQUENCE MASSAGE_SEQ;
DROP TABLE CHATROOM;
DROP TABLE CHATLIST;
DROP TABLE MASSAGE;


CREATE SEQUENCE CHATROOM_SEQ;
CREATE SEQUENCE CHATlIST_SEQ;
CREATE SEQUENCE MASSAGE_SEQ;

CREATE TABLE CHATROOM(
	CHATROOM_NO NUMBER PRIMARY KEY,
	CHATROOM_TITLE VARCHAR2(500),
	CHATROOM_TOTALCOUNT NUMBER
);

CREATE TABLE CHATLIST(
	CHATLIST_NO NUMBER PRIMARY KEY,
	CHATROOM_NO NUMBER REFERENCES CHATROOM(CHATROOM_NO),
	MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO)
);

CREATE TABLE MASSAGE(
	MASSAGE_NO NUMBER PRIMARY KEY,
	CHATROOM_NO NUMBER REFERENCES CHATROOM(CHATROOM_NO),
	MASSAGE_CONTENT VARCHAR2(1000),
	MASSAGE_REGTIME DATE
);

INSERT INTO CHATROOM VALUES(CHATROOM_SEQ.NEXTVAL, '첫번째 채팅방', 0);
INSERT INTO CHATROOM VALUES(CHATROOM_SEQ.NEXTVAL, '두번째 채팅방', 0);
INSERT INTO CHATROOM VALUES(CHATROOM_SEQ.NEXTVAL, '세번째 채팅방', 0);
INSERT INTO CHATROOM VALUES(CHATROOM_SEQ.NEXTVAL, '네번째 채팅방', 0);

SELECT * FROM CHATROOM;
SELECT * FROM CHATLIST;
SELECT * FROM MASSAGE;

SELECT COUNT(MEMBER_NO) FROM CHATLIST WHERE CHATROOM_NO = 6;

INSERT INTO CHATLIST VALUES(CHATLIST_SEQ.NEXTVAL, 1, 1);

SELECT * FROM MASSAGE WHERE CHATROOM_NO = 1 ORDER BY MASSAGE_NO; 

