DROP SEQUENCE HOUSE_SEQ;
DROP TABLE HOUSE;

CREATE SEQUENCE HOUSE_SEQ;
CREATE TABLE HOUSE(
	HOUSE_ID NUMBER PRIMARY KEY,
	HOUSE_KEEPER NUMBER REFERENCES MEMBER(MEMBER_NO),
	HOUSE_NAME VARCHAR2(30) NOT NULL,
	HOUSE_PHONE VARCHAR2(30) NOT NULL,
	HOUSE_ADDR VARCHAR2(1000) NOT NULL,
	HOUSE_IMAGE VARCHAR2(4000),
	HOUSE_CONTENT VARCHAR2(3000),
	HOUSE_DOCUMENT VARCHAR2(3000) NOT NULL,
	HOUSE_STATUS VARCHAR2(2) NOT NULL
);

INSERT INTO HOUSE VALUES(
	HOUSE_SEQ.NEXTVAL, 1,'푸르지오','032-651-5002','중동역','defaulthouse.jpg','좋다','없다','1'
);



SELECT * FROM HOUSE;
