DROP SEQUENCE PLAN_SEQ;
DROP TABLE PLAN;

CREATE SEQUENCE PLAN_SEQ;
CREATE TABLE PLAN(
	PLAN_NO NUMBER PRIMARY KEY,
	HOUSE_ID NUMBER REFERENCES HOUSE(HOUSE_ID),
	PLAN_TITLE VARCHAR2(100) NOT NULL,
	PLAN_START VARCHAR2(30) NOT NULL,
	PLAN_END VARCHAR2(30)
);

INSERT INTO PLAN VALUES(
	PLAN_SEQ.NEXTVAL,1,'바베큐PARTY','2020-05-14','2020-05-16'
);

SELECT * FROM PLAN;
SELECT * FROM HOUSE;
SELECT * FROM PLAN WHERE HOUSE_ID = 1;

DELETE FROM PLAN WHERE PLAN_NO = 72;

