--댓글번호, 게시글번호(외래키), 작성자(외래키), 내용, 작성일
DROP TABLE REPLY;

CREATE SEQUENCE REPLY_SEQ;

CREATE TABLE REPLY(
	REPLY_NO NUMBER PRIMARY KEY,
	BOARD_NO NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	REPLY_CONTENT VARCHAR2(200) NOT NULL,
	REPLY_REGDATE DATE NOT NULL,
	
	CONSTRAINT BOARD_NO_FK FOREIGN KEY(BOARD_NO)
	REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
	
	CONSTRAINT MEMBER_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
	--글이 지워지면 해당 답글도 지워져야 한다.
	--article_number > delete option : cascade
);


SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM REPLY;
SELECT * FROM TAB;
